{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "7.5"
    }
  },
  "component" : {
    "group" : "com.github.horizontalsystems",
    "module" : "market-kit-android",
    "version" : "a0361bf",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "releaseVariantReleaseApiPublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-api"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib-jdk8",
      "version" : {
        "requires" : "1.6.21"
      }
    } ],
    "files" : [ {
      "name" : "market-kit-android-a0361bf.aar",
      "url" : "market-kit-android-a0361bf.aar",
      "size" : 812867,
      "sha512" : "bfd1910211395eb6e8d4265d5d56809249ca2451366a1bfde72f92727a65ec230302e2d01e727ffe518669cc67eb1162937c2a15ca015531b4ff183befbb1f2a",
      "sha256" : "3e31c790a2909401a4562708424d9f997b7758406ae4f718b4118e7cd8c86765",
      "sha1" : "aa79e539ad87d434af270a0f5c95b16802a8ed03",
      "md5" : "d856d53be72cc2295b29c45ce6bf8650"
    } ]
  }, {
    "name" : "releaseVariantReleaseRuntimePublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-parcelize-runtime",
      "version" : {
        "requires" : "1.6.21"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib-jdk8",
      "version" : {
        "requires" : "1.6.21"
      }
    }, {
      "group" : "androidx.core",
      "module" : "core-ktx",
      "version" : {
        "requires" : "1.7.0"
      }
    }, {
      "group" : "androidx.appcompat",
      "module" : "appcompat",
      "version" : {
        "requires" : "1.4.1"
      }
    }, {
      "group" : "com.google.android.material",
      "module" : "material",
      "version" : {
        "requires" : "1.5.0"
      }
    }, {
      "group" : "androidx.room",
      "module" : "room-runtime",
      "version" : {
        "requires" : "2.4.2"
      }
    }, {
      "group" : "androidx.room",
      "module" : "room-rxjava2",
      "version" : {
        "requires" : "2.4.2"
      }
    }, {
      "group" : "io.reactivex.rxjava2",
      "module" : "rxjava",
      "version" : {
        "requires" : "2.2.19"
      }
    }, {
      "group" : "io.reactivex.rxjava2",
      "module" : "rxandroid",
      "version" : {
        "requires" : "2.1.1"
      }
    }, {
      "group" : "com.squareup.retrofit2",
      "module" : "retrofit",
      "version" : {
        "requires" : "2.9.0"
      }
    }, {
      "group" : "com.squareup.retrofit2",
      "module" : "adapter-rxjava2",
      "version" : {
        "requires" : "2.9.0"
      }
    }, {
      "group" : "com.squareup.retrofit2",
      "module" : "converter-gson",
      "version" : {
        "requires" : "2.9.0"
      }
    }, {
      "group" : "com.squareup.okhttp3",
      "module" : "logging-interceptor",
      "version" : {
        "requires" : "4.9.0"
      }
    }, {
      "group" : "com.squareup.retrofit2",
      "module" : "converter-scalars",
      "version" : {
        "requires" : "2.9.0"
      }
    }, {
      "group" : "com.google.code.gson",
      "module" : "gson",
      "version" : {
        "requires" : "2.8.9"
      }
    } ],
    "files" : [ {
      "name" : "market-kit-android-a0361bf.aar",
      "url" : "market-kit-android-a0361bf.aar",
      "size" : 812867,
      "sha512" : "bfd1910211395eb6e8d4265d5d56809249ca2451366a1bfde72f92727a65ec230302e2d01e727ffe518669cc67eb1162937c2a15ca015531b4ff183befbb1f2a",
      "sha256" : "3e31c790a2909401a4562708424d9f997b7758406ae4f718b4118e7cd8c86765",
      "sha1" : "aa79e539ad87d434af270a0f5c95b16802a8ed03",
      "md5" : "d856d53be72cc2295b29c45ce6bf8650"
    } ]
  } ]
}